Implemented lineage only mode
TRON-Bioinformatics/covigator-ngs-pipeline pull request #54
Opened 2023-09-28 11:20 UTC by johausmann

* Implementation of create reference only mode (Related to comment in #50) 
* Implementation of pangolin/lineage only mode to call pangolin for VCF or FASTA input. Closes #51

2023-09-28 21:06 UTC, priesgo requested changes
Would you please add tests to the CI that test for `reference_generate` and `lineage_mode`? 

Through automated tests you make sure that it works now and that if it's broken later on we know it before it's merged.

2023-10-05 13:20 UTC, johausmann commented on main.nf
> +if (params.lineage_mode && input_fastqs) {
That's true, but don't the files from --fastq1 and --fastq2 also end up in `input_fastqs`? Depending on the input, isn't the created channel set to `input_fastqs` with ` .set{ input_fastqs}` ?

2023-10-10 11:19 UTC, johausmann commented
Okay, I've addressed the issues. Let me know if anything else is missing

2023-10-10 16:11 UTC, priesgo approved these changes
Perfect!

2023-10-10 16:11 UTC, merged